# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# after completion it'll publish the build artifacts

name: Java CI publish artifact

on:
  push:
      branches:
          - '*'
          - '*/*'
          - '**'
      tags:
          - v1.*

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: target/*.jar
      -name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}


