# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# after completion it'll publish and release the build artifacts and deploy to aws

name: Java CD deploy artifact

on:
  push:
      tags:
          - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: target/*.jar
      - name: Get Version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/NarutoDB.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Artifacts
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: NarutoDB
          environment_name: Narutodb-env
          version_label: ${{ steps.vars.outputs.tag }}
          region: ap-south-1
          deployment_package: "target/NarutoDB.jar"
